export const mcpTools = [
  { name: "drive_list", description: "Read-only: list items in a folder. Returns bounded metadata and a pagination cursor.", annotations: { readOnlyHint: true, destructiveHint: false }, inputSchema: { type: "object", properties: { parent_id: { type: "string" }, cursor: { type: "string" }, limit: { type: "integer", minimum: 1, maximum: 100 }, include_trash: { type: "boolean" } } } },
  { name: "drive_search", description: "Read-only: search active files and folders by filename.", annotations: { readOnlyHint: true, destructiveHint: false }, inputSchema: { type: "object", required: ["query"], properties: { query: { type: "string" }, cursor: { type: "string" }, limit: { type: "integer", minimum: 1, maximum: 100 } } } },
  { name: "drive_get_metadata", description: "Read-only: get metadata for one file or folder.", annotations: { readOnlyHint: true, destructiveHint: false }, inputSchema: { type: "object", required: ["id"], properties: { id: { type: "string" } } } },
  { name: "drive_read_text", description: "Read-only: read a bounded UTF-8 text file, limited to the configured MCP read size.", annotations: { readOnlyHint: true, destructiveHint: false }, inputSchema: { type: "object", required: ["id"], properties: { id: { type: "string" } } } },
  { name: "drive_write_file", description: "Write: create or conditionally overwrite a small UTF-8 or base64 file. Large binary transfers use REST upload/download.", annotations: { readOnlyHint: false, destructiveHint: false }, inputSchema: { type: "object", required: ["name", "content"], properties: { name: { type: "string" }, parent_id: { type: "string" }, content: { type: "string" }, encoding: { type: "string", enum: ["utf8", "base64"] }, mime_type: { type: "string" }, overwrite_id: { type: "string" }, if_match: { type: "string" } } } },
  { name: "drive_create_folder", description: "Write: create a folder, failing on duplicate names.", annotations: { readOnlyHint: false, destructiveHint: false }, inputSchema: { type: "object", required: ["name"], properties: { name: { type: "string" }, parent_id: { type: "string" } } } },
  { name: "drive_rename_item", description: "Write: rename a file or folder. Fails on duplicate names.", annotations: { readOnlyHint: false, destructiveHint: false }, inputSchema: { type: "object", required: ["id", "name"], properties: { id: { type: "string" }, name: { type: "string" }, if_match: { type: "string" } } } },
  { name: "drive_move_item", description: "Write: move a file or folder into another folder. Fails on cycles and duplicate names.", annotations: { readOnlyHint: false, destructiveHint: false }, inputSchema: { type: "object", required: ["id", "parent_id"], properties: { id: { type: "string" }, parent_id: { type: "string" }, if_match: { type: "string" } } } },
  { name: "drive_trash_item", description: "Destructive: soft-delete an item and its entire subtree. This can be restored.", annotations: { readOnlyHint: false, destructiveHint: true }, inputSchema: { type: "object", required: ["id"], properties: { id: { type: "string" } } } },
  { name: "drive_restore_item", description: "Write: restore a trashed item and its subtree atomically; fails on name conflicts.", annotations: { readOnlyHint: false, destructiveHint: false }, inputSchema: { type: "object", required: ["id"], properties: { id: { type: "string" } } } },
  { name: "drive_delete_permanently", description: "Destructive: permanently delete an item, its subtree, metadata, and stored bytes. This cannot be undone.", annotations: { readOnlyHint: false, destructiveHint: true }, inputSchema: { type: "object", required: ["id"], properties: { id: { type: "string" } } } },
] as const;
